import { SPECIES } from "../pokemon/data/Species"
import { MOVE } from "./data/Moves"

export const EggMoves: MOVE[][] = []

EggMoves[SPECIES.BULBASAUR] = [
    MOVE.LIGHT_SCREEN,
    MOVE.SKULL_BASH,
    MOVE.SAFEGUARD,
    MOVE.CHARM,
    MOVE.PETAL_DANCE,
    MOVE.MAGICAL_LEAF,
    MOVE.GRASS_WHISTLE,
    MOVE.CURSE
]
EggMoves[SPECIES.CHARMANDER] = [
    MOVE.BELLY_DRUM,
    MOVE.ANCIENT_POWER,
    MOVE.ROCK_SLIDE,
    MOVE.BITE,
    MOVE.OUTRAGE,
    MOVE.BEAT_UP,
    MOVE.SWORDS_DANCE,
    MOVE.DRAGON_DANCE
]
EggMoves[SPECIES.SQUIRTLE] = [
    MOVE.MIRROR_COAT,
    MOVE.HAZE,
    MOVE.MIST,
    MOVE.FORESIGHT,
    MOVE.FLAIL,
    MOVE.REFRESH,
    MOVE.MUD_SPORT,
    MOVE.YAWN
]
EggMoves[SPECIES.PIDGEY] = [
    MOVE.PURSUIT,
    MOVE.FAINT_ATTACK,
    MOVE.FORESIGHT,
    MOVE.STEEL_WING,
    MOVE.AIR_CUTTER
]
EggMoves[SPECIES.RATTATA] = [
    MOVE.SCREECH,
    MOVE.FLAME_WHEEL,
    MOVE.FURY_SWIPES,
    MOVE.BITE,
    MOVE.COUNTER,
    MOVE.REVERSAL,
    MOVE.UPROAR,
    MOVE.SWAGGER
]
EggMoves[SPECIES.SPEAROW] = [
    MOVE.FAINT_ATTACK,
    MOVE.FALSE_SWIPE,
    MOVE.SCARY_FACE,
    MOVE.QUICK_ATTACK,
    MOVE.TRI_ATTACK,
    MOVE.ASTONISH,
    MOVE.SKY_ATTACK
]
EggMoves[SPECIES.EKANS] = [
    MOVE.PURSUIT,
    MOVE.SLAM,
    MOVE.SPITE,
    MOVE.BEAT_UP,
    MOVE.POISON_FANG
]
EggMoves[SPECIES.SANDSHREW] = [
    MOVE.FLAIL,
    MOVE.SAFEGUARD,
    MOVE.COUNTER,
    MOVE.RAPID_SPIN,
    MOVE.ROCK_SLIDE,
    MOVE.METAL_CLAW,
    MOVE.SWORDS_DANCE,
    MOVE.CRUSH_CLAW
]
EggMoves[SPECIES.NIDORAN_F] = [
    MOVE.SUPERSONIC,
    MOVE.DISABLE,
    MOVE.TAKE_DOWN,
    MOVE.FOCUS_ENERGY,
    MOVE.CHARM,
    MOVE.COUNTER,
    MOVE.BEAT_UP
]
EggMoves[SPECIES.NIDORAN_M] = [
    MOVE.COUNTER,
    MOVE.DISABLE,
    MOVE.SUPERSONIC,
    MOVE.TAKE_DOWN,
    MOVE.AMNESIA,
    MOVE.CONFUSION,
    MOVE.BEAT_UP
]
EggMoves[SPECIES.VULPIX] = [
    MOVE.FAINT_ATTACK,
    MOVE.HYPNOSIS,
    MOVE.FLAIL,
    MOVE.SPITE,
    MOVE.DISABLE,
    MOVE.HOWL,
    MOVE.PSYCH_UP,
    MOVE.HEAT_WAVE
]
EggMoves[SPECIES.ZUBAT] = [
    MOVE.QUICK_ATTACK,
    MOVE.PURSUIT,
    MOVE.FAINT_ATTACK,
    MOVE.GUST,
    MOVE.WHIRLWIND,
    MOVE.CURSE
]
EggMoves[SPECIES.ODDISH] = [
    MOVE.SWORDS_DANCE,
    MOVE.RAZOR_LEAF,
    MOVE.FLAIL,
    MOVE.SYNTHESIS,
    MOVE.CHARM,
    MOVE.INGRAIN
]
EggMoves[SPECIES.PARAS] = [
    MOVE.FALSE_SWIPE,
    MOVE.SCREECH,
    MOVE.COUNTER,
    MOVE.PSYBEAM,
    MOVE.FLAIL,
    MOVE.SWEET_SCENT,
    MOVE.LIGHT_SCREEN,
    MOVE.PURSUIT
]
EggMoves[SPECIES.VENONAT] = [
    MOVE.BATON_PASS,
    MOVE.SCREECH,
    MOVE.GIGA_DRAIN,
    MOVE.SIGNAL_BEAM
]
EggMoves[SPECIES.DIGLETT] = [
    MOVE.FAINT_ATTACK,
    MOVE.SCREECH,
    MOVE.ANCIENT_POWER,
    MOVE.PURSUIT,
    MOVE.BEAT_UP,
    MOVE.UPROAR,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.MEOWTH] = [
    MOVE.SPITE,
    MOVE.CHARM,
    MOVE.HYPNOSIS,
    MOVE.AMNESIA,
    MOVE.PSYCH_UP,
    MOVE.ASSIST
]
EggMoves[SPECIES.PSYDUCK] = [
    MOVE.HYPNOSIS,
    MOVE.PSYBEAM,
    MOVE.FORESIGHT,
    MOVE.LIGHT_SCREEN,
    MOVE.FUTURE_SIGHT,
    MOVE.PSYCHIC,
    MOVE.CROSS_CHOP,
    MOVE.REFRESH
]
EggMoves[SPECIES.MANKEY] = [
    MOVE.ROCK_SLIDE,
    MOVE.FORESIGHT,
    MOVE.MEDITATE,
    MOVE.COUNTER,
    MOVE.REVERSAL,
    MOVE.BEAT_UP,
    MOVE.REVENGE,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.GROWLITHE] = [
    MOVE.BODY_SLAM,
    MOVE.SAFEGUARD,
    MOVE.CRUNCH,
    MOVE.THRASH,
    MOVE.FIRE_SPIN,
    MOVE.HOWL,
    MOVE.HEAT_WAVE
]
EggMoves[SPECIES.POLIWAG] = [
    MOVE.MIST,
    MOVE.SPLASH,
    MOVE.BUBBLE_BEAM,
    MOVE.HAZE,
    MOVE.MIND_READER,
    MOVE.WATER_SPORT,
    MOVE.ICE_BALL
]
EggMoves[SPECIES.ABRA] = [
    MOVE.ENCORE,
    MOVE.BARRIER,
    MOVE.KNOCK_OFF,
    MOVE.FIRE_PUNCH,
    MOVE.THUNDER_PUNCH,
    MOVE.ICE_PUNCH
]
EggMoves[SPECIES.MACHOP] = [
    MOVE.LIGHT_SCREEN,
    MOVE.MEDITATE,
    MOVE.ROLLING_KICK,
    MOVE.ENCORE,
    MOVE.SMELLING_SALT,
    MOVE.COUNTER,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.BELLSPROUT] = [
    MOVE.SWORDS_DANCE,
    MOVE.ENCORE,
    MOVE.REFLECT,
    MOVE.SYNTHESIS,
    MOVE.LEECH_LIFE,
    MOVE.INGRAIN,
    MOVE.MAGICAL_LEAF
]
EggMoves[SPECIES.TENTACOOL] = [
    MOVE.AURORA_BEAM,
    MOVE.MIRROR_COAT,
    MOVE.RAPID_SPIN,
    MOVE.HAZE,
    MOVE.SAFEGUARD,
    MOVE.CONFUSE_RAY
]
EggMoves[SPECIES.GEODUDE] = [
    MOVE.MEGA_PUNCH,
    MOVE.ROCK_SLIDE,
    MOVE.BLOCK
]
EggMoves[SPECIES.PONYTA] = [
    MOVE.FLAME_WHEEL,
    MOVE.THRASH,
    MOVE.DOUBLE_KICK,
    MOVE.HYPNOSIS,
    MOVE.CHARM,
    MOVE.DOUBLE_EDGE
]
EggMoves[SPECIES.SLOWPOKE] = [
    MOVE.SAFEGUARD,
    MOVE.BELLY_DRUM,
    MOVE.FUTURE_SIGHT,
    MOVE.STOMP,
    MOVE.MUD_SPORT,
    MOVE.SLEEP_TALK,
    MOVE.SNORE
]
EggMoves[SPECIES.FARFETCHD] = [
    MOVE.STEEL_WING,
    MOVE.FORESIGHT,
    MOVE.MIRROR_MOVE,
    MOVE.GUST,
    MOVE.QUICK_ATTACK,
    MOVE.FLAIL,
    MOVE.FEATHER_DANCE,
    MOVE.CURSE
]
EggMoves[SPECIES.DODUO] = [
    MOVE.QUICK_ATTACK,
    MOVE.SUPERSONIC,
    MOVE.HAZE,
    MOVE.FAINT_ATTACK,
    MOVE.FLAIL,
    MOVE.ENDEAVOR
]
EggMoves[SPECIES.SEEL] = [
    MOVE.LICK,
    MOVE.PERISH_SONG,
    MOVE.DISABLE,
    MOVE.HORN_DRILL,
    MOVE.SLAM,
    MOVE.ENCORE,
    MOVE.FAKE_OUT,
    MOVE.ICICLE_SPEAR
]
EggMoves[SPECIES.GRIMER] = [
    MOVE.HAZE,
    MOVE.MEAN_LOOK,
    MOVE.LICK,
    MOVE.IMPRISON,
    MOVE.CURSE,
    MOVE.SHADOW_PUNCH,
    MOVE.EXPLOSION
]
EggMoves[SPECIES.SHELLDER] = [
    MOVE.BUBBLE_BEAM,
    MOVE.TAKE_DOWN,
    MOVE.BARRIER,
    MOVE.RAPID_SPIN,
    MOVE.SCREECH,
    MOVE.ICICLE_SPEAR
]
EggMoves[SPECIES.GASTLY] = [
    MOVE.PSYWAVE,
    MOVE.PERISH_SONG,
    MOVE.HAZE,
    MOVE.ASTONISH,
    MOVE.WILL_O_WISP,
    MOVE.GRUDGE,
    MOVE.EXPLOSION
]
EggMoves[SPECIES.ONIX] = [
    MOVE.ROCK_SLIDE,
    MOVE.FLAIL,
    MOVE.EXPLOSION,
    MOVE.BLOCK
]
EggMoves[SPECIES.DROWZEE] = [
    MOVE.BARRIER,
    MOVE.ASSIST,
    MOVE.ROLE_PLAY,
    MOVE.FIRE_PUNCH,
    MOVE.THUNDER_PUNCH,
    MOVE.ICE_PUNCH
]
EggMoves[SPECIES.KRABBY] = [
    MOVE.DIG,
    MOVE.HAZE,
    MOVE.AMNESIA,
    MOVE.FLAIL,
    MOVE.SLAM,
    MOVE.KNOCK_OFF,
    MOVE.SWORDS_DANCE
]
EggMoves[SPECIES.EXEGGCUTE] = [
    MOVE.SYNTHESIS,
    MOVE.MOONLIGHT,
    MOVE.REFLECT,
    MOVE.ANCIENT_POWER,
    MOVE.PSYCH_UP,
    MOVE.INGRAIN,
    MOVE.CURSE
]
EggMoves[SPECIES.CUBONE] = [
    MOVE.ROCK_SLIDE,
    MOVE.ANCIENT_POWER,
    MOVE.BELLY_DRUM,
    MOVE.SCREECH,
    MOVE.SKULL_BASH,
    MOVE.PERISH_SONG,
    MOVE.SWORDS_DANCE
]
EggMoves[SPECIES.LICKITUNG] = [
    MOVE.BELLY_DRUM,
    MOVE.MAGNITUDE,
    MOVE.BODY_SLAM,
    MOVE.CURSE,
    MOVE.SMELLING_SALT,
    MOVE.SLEEP_TALK,
    MOVE.SNORE,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.KOFFING] = [
    MOVE.SCREECH,
    MOVE.PSYWAVE,
    MOVE.PSYBEAM,
    MOVE.DESTINY_BOND,
    MOVE.PAIN_SPLIT,
    MOVE.WILL_O_WISP
]
EggMoves[SPECIES.RHYHORN] = [
    MOVE.CRUNCH,
    MOVE.REVERSAL,
    MOVE.ROCK_SLIDE,
    MOVE.COUNTER,
    MOVE.MAGNITUDE,
    MOVE.SWORDS_DANCE,
    MOVE.CURSE,
    MOVE.CRUSH_CLAW
]
EggMoves[SPECIES.CHANSEY] = [
    MOVE.PRESENT,
    MOVE.METRONOME,
    MOVE.HEAL_BELL,
    MOVE.AROMATHERAPY,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.TANGELA] = [
    MOVE.FLAIL,
    MOVE.CONFUSION,
    MOVE.MEGA_DRAIN,
    MOVE.REFLECT,
    MOVE.AMNESIA,
    MOVE.LEECH_SEED,
    MOVE.NATURE_POWER
]
EggMoves[SPECIES.KANGASKHAN] = [
    MOVE.STOMP,
    MOVE.FORESIGHT,
    MOVE.FOCUS_ENERGY,
    MOVE.SAFEGUARD,
    MOVE.DISABLE,
    MOVE.COUNTER,
    MOVE.CRUSH_CLAW,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.HORSEA] = [
    MOVE.FLAIL,
    MOVE.AURORA_BEAM,
    MOVE.OCTAZOOKA,
    MOVE.DISABLE,
    MOVE.SPLASH,
    MOVE.DRAGON_RAGE,
    MOVE.DRAGON_BREATH
]
EggMoves[SPECIES.GOLDEEN] = [
    MOVE.PSYBEAM,
    MOVE.HAZE,
    MOVE.HYDRO_PUMP,
    MOVE.SLEEP_TALK,
    MOVE.MUD_SPORT
]
EggMoves[SPECIES.MR_MIME] = [
    MOVE.FUTURE_SIGHT,
    MOVE.HYPNOSIS,
    MOVE.MIMIC,
    MOVE.PSYCH_UP,
    MOVE.FAKE_OUT,
    MOVE.TRICK
]
EggMoves[SPECIES.SCYTHER] = [
    MOVE.COUNTER,
    MOVE.SAFEGUARD,
    MOVE.BATON_PASS,
    MOVE.RAZOR_WIND,
    MOVE.REVERSAL,
    MOVE.LIGHT_SCREEN,
    MOVE.ENDURE,
    MOVE.SILVER_WIND
]
EggMoves[SPECIES.PINSIR] = [
    MOVE.FURY_ATTACK,
    MOVE.FLAIL,
    MOVE.FALSE_SWIPE,
    MOVE.FAINT_ATTACK
]
EggMoves[SPECIES.LAPRAS] = [
    MOVE.FORESIGHT,
    MOVE.SUBSTITUTE,
    MOVE.TICKLE,
    MOVE.REFRESH,
    MOVE.DRAGON_DANCE,
    MOVE.CURSE,
    MOVE.SLEEP_TALK,
    MOVE.HORN_DRILL
]
EggMoves[SPECIES.EEVEE] = [
    MOVE.CHARM,
    MOVE.FLAIL,
    MOVE.ENDURE,
    MOVE.CURSE,
    MOVE.TICKLE,
    MOVE.WISH
]
EggMoves[SPECIES.OMANYTE] = [
    MOVE.BUBBLE_BEAM,
    MOVE.AURORA_BEAM,
    MOVE.SLAM,
    MOVE.SUPERSONIC,
    MOVE.HAZE,
    MOVE.ROCK_SLIDE,
    MOVE.SPIKES
]
EggMoves[SPECIES.KABUTO] = [
    MOVE.BUBBLE_BEAM,
    MOVE.AURORA_BEAM,
    MOVE.RAPID_SPIN,
    MOVE.DIG,
    MOVE.FLAIL,
    MOVE.KNOCK_OFF,
    MOVE.CONFUSE_RAY
]
EggMoves[SPECIES.AERODACTYL] = [
    MOVE.WHIRLWIND,
    MOVE.PURSUIT,
    MOVE.FORESIGHT,
    MOVE.STEEL_WING,
    MOVE.DRAGON_BREATH,
    MOVE.CURSE
]
EggMoves[SPECIES.SNORLAX] = [
    MOVE.LICK,
    MOVE.CHARM,
    MOVE.DOUBLE_EDGE,
    MOVE.CURSE,
    MOVE.FISSURE,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.DRATINI] = [
    MOVE.LIGHT_SCREEN,
    MOVE.MIST,
    MOVE.HAZE,
    MOVE.SUPERSONIC,
    MOVE.DRAGON_BREATH,
    MOVE.DRAGON_DANCE
]
EggMoves[SPECIES.CHIKORITA] = [
    MOVE.VINE_WHIP,
    MOVE.LEECH_SEED,
    MOVE.COUNTER,
    MOVE.ANCIENT_POWER,
    MOVE.FLAIL,
    MOVE.NATURE_POWER,
    MOVE.INGRAIN,
    MOVE.GRASS_WHISTLE
]
EggMoves[SPECIES.CYNDAQUIL] = [
    MOVE.FURY_SWIPES,
    MOVE.QUICK_ATTACK,
    MOVE.REVERSAL,
    MOVE.THRASH,
    MOVE.FORESIGHT,
    MOVE.COVET,
    MOVE.HOWL,
    MOVE.CRUSH_CLAW
]
EggMoves[SPECIES.TOTODILE] = [
    MOVE.CRUNCH,
    MOVE.THRASH,
    MOVE.HYDRO_PUMP,
    MOVE.ANCIENT_POWER,
    MOVE.ROCK_SLIDE,
    MOVE.MUD_SPORT,
    MOVE.WATER_SPORT,
    MOVE.DRAGON_CLAW
]
EggMoves[SPECIES.SENTRET] = [
    MOVE.DOUBLE_EDGE,
    MOVE.PURSUIT,
    MOVE.SLASH,
    MOVE.FOCUS_ENERGY,
    MOVE.REVERSAL,
    MOVE.SUBSTITUTE,
    MOVE.TRICK,
    MOVE.ASSIST
]
EggMoves[SPECIES.HOOTHOOT] = [
    MOVE.MIRROR_MOVE,
    MOVE.SUPERSONIC,
    MOVE.FAINT_ATTACK,
    MOVE.WING_ATTACK,
    MOVE.WHIRLWIND,
    MOVE.SKY_ATTACK,
    MOVE.FEATHER_DANCE
]
EggMoves[SPECIES.LEDYBA] = [
    MOVE.PSYBEAM,
    MOVE.BIDE,
    MOVE.SILVER_WIND
]
EggMoves[SPECIES.SPINARAK] = [
    MOVE.PSYBEAM,
    MOVE.DISABLE,
    MOVE.SONIC_BOOM,
    MOVE.BATON_PASS,
    MOVE.PURSUIT,
    MOVE.SIGNAL_BEAM
]
EggMoves[SPECIES.CHINCHOU] = [
    MOVE.FLAIL,
    MOVE.SCREECH,
    MOVE.AMNESIA
]
EggMoves[SPECIES.PICHU] = [
    MOVE.REVERSAL,
    MOVE.BIDE,
    MOVE.PRESENT,
    MOVE.ENCORE,
    MOVE.DOUBLE_SLAP,
    MOVE.WISH,
    MOVE.CHARGE
]
EggMoves[SPECIES.CLEFFA] = [
    MOVE.PRESENT,
    MOVE.METRONOME,
    MOVE.AMNESIA,
    MOVE.BELLY_DRUM,
    MOVE.SPLASH,
    MOVE.MIMIC,
    MOVE.WISH,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.IGGLYBUFF] = [
    MOVE.PERISH_SONG,
    MOVE.PRESENT,
    MOVE.FAINT_ATTACK,
    MOVE.WISH,
    MOVE.FAKE_TEARS
]
EggMoves[SPECIES.TOGEPI] = [
    MOVE.PRESENT,
    MOVE.MIRROR_MOVE,
    MOVE.PECK,
    MOVE.FORESIGHT,
    MOVE.FUTURE_SIGHT,
    MOVE.SUBSTITUTE,
    MOVE.PSYCH_UP
]
EggMoves[SPECIES.NATU] = [
    MOVE.HAZE,
    MOVE.DRILL_PECK,
    MOVE.QUICK_ATTACK,
    MOVE.FAINT_ATTACK,
    MOVE.STEEL_WING,
    MOVE.PSYCH_UP,
    MOVE.FEATHER_DANCE,
    MOVE.REFRESH
]
EggMoves[SPECIES.MAREEP] = [
    MOVE.TAKE_DOWN,
    MOVE.BODY_SLAM,
    MOVE.SAFEGUARD,
    MOVE.SCREECH,
    MOVE.REFLECT,
    MOVE.ODOR_SLEUTH,
    MOVE.CHARGE
]
EggMoves[SPECIES.MARILL] = [
    MOVE.LIGHT_SCREEN,
    MOVE.PRESENT,
    MOVE.AMNESIA,
    MOVE.FUTURE_SIGHT,
    MOVE.BELLY_DRUM,
    MOVE.PERISH_SONG,
    MOVE.SUPERSONIC,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.SUDOWOODO] = [
    MOVE.SELF_DESTRUCT
]
EggMoves[SPECIES.HOPPIP] = [
    MOVE.CONFUSION,
    MOVE.ENCORE,
    MOVE.DOUBLE_EDGE,
    MOVE.REFLECT,
    MOVE.AMNESIA,
    MOVE.HELPING_HAND,
    MOVE.PSYCH_UP
]
EggMoves[SPECIES.AIPOM] = [
    MOVE.COUNTER,
    MOVE.SCREECH,
    MOVE.PURSUIT,
    MOVE.AGILITY,
    MOVE.SPITE,
    MOVE.SLAM,
    MOVE.DOUBLE_SLAP,
    MOVE.BEAT_UP
]
EggMoves[SPECIES.SUNKERN] = [
    MOVE.GRASS_WHISTLE,
    MOVE.ENCORE,
    MOVE.LEECH_SEED,
    MOVE.NATURE_POWER,
    MOVE.CURSE,
    MOVE.HELPING_HAND
]
EggMoves[SPECIES.YANMA] = [
    MOVE.WHIRLWIND,
    MOVE.REVERSAL,
    MOVE.LEECH_LIFE,
    MOVE.SIGNAL_BEAM,
    MOVE.SILVER_WIND
]
EggMoves[SPECIES.WOOPER] = [
    MOVE.BODY_SLAM,
    MOVE.ANCIENT_POWER,
    MOVE.SAFEGUARD,
    MOVE.CURSE,
    MOVE.MUD_SPORT,
    MOVE.STOCKPILE,
    MOVE.SWALLOW,
    MOVE.SPIT_UP
]
EggMoves[SPECIES.MURKROW] = [
    MOVE.WHIRLWIND,
    MOVE.DRILL_PECK,
    MOVE.MIRROR_MOVE,
    MOVE.WING_ATTACK,
    MOVE.SKY_ATTACK,
    MOVE.CONFUSE_RAY,
    MOVE.FEATHER_DANCE,
    MOVE.PERISH_SONG
]
EggMoves[SPECIES.MISDREAVUS] = [
    MOVE.SCREECH,
    MOVE.DESTINY_BOND,
    MOVE.PSYCH_UP,
    MOVE.IMPRISON
]
EggMoves[SPECIES.GIRAFARIG] = [
    MOVE.TAKE_DOWN,
    MOVE.AMNESIA,
    MOVE.FORESIGHT,
    MOVE.FUTURE_SIGHT,
    MOVE.BEAT_UP,
    MOVE.PSYCH_UP,
    MOVE.WISH,
    MOVE.MAGIC_COAT
]
EggMoves[SPECIES.PINECO] = [
    MOVE.REFLECT,
    MOVE.PIN_MISSILE,
    MOVE.FLAIL,
    MOVE.SWIFT,
    MOVE.COUNTER,
    MOVE.SAND_TOMB
]
EggMoves[SPECIES.DUNSPARCE] = [
    MOVE.BIDE,
    MOVE.ANCIENT_POWER,
    MOVE.ROCK_SLIDE,
    MOVE.BITE,
    MOVE.HEADBUTT,
    MOVE.ASTONISH,
    MOVE.CURSE
]
EggMoves[SPECIES.GLIGAR] = [
    MOVE.METAL_CLAW,
    MOVE.WING_ATTACK,
    MOVE.RAZOR_WIND,
    MOVE.COUNTER,
    MOVE.SAND_TOMB
]
EggMoves[SPECIES.SNUBBULL] = [
    MOVE.METRONOME,
    MOVE.FAINT_ATTACK,
    MOVE.REFLECT,
    MOVE.PRESENT,
    MOVE.CRUNCH,
    MOVE.HEAL_BELL,
    MOVE.SNORE,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.QWILFISH] = [
    MOVE.FLAIL,
    MOVE.HAZE,
    MOVE.BUBBLE_BEAM,
    MOVE.SUPERSONIC,
    MOVE.ASTONISH
]
EggMoves[SPECIES.SHUCKLE] = [
    MOVE.SWEET_SCENT
]
EggMoves[SPECIES.HERACROSS] = [
    MOVE.HARDEN,
    MOVE.BIDE,
    MOVE.FLAIL,
    MOVE.FALSE_SWIPE
]
EggMoves[SPECIES.SNEASEL] = [
    MOVE.COUNTER,
    MOVE.SPITE,
    MOVE.FORESIGHT,
    MOVE.REFLECT,
    MOVE.BITE,
    MOVE.CRUSH_CLAW,
    MOVE.FAKE_OUT
]
EggMoves[SPECIES.TEDDIURSA] = [
    MOVE.CRUNCH,
    MOVE.TAKE_DOWN,
    MOVE.SEISMIC_TOSS,
    MOVE.COUNTER,
    MOVE.METAL_CLAW,
    MOVE.FAKE_TEARS,
    MOVE.YAWN,
    MOVE.SLEEP_TALK
]
EggMoves[SPECIES.SLUGMA] = [
    MOVE.ACID_ARMOR,
    MOVE.HEAT_WAVE
]
EggMoves[SPECIES.SWINUB] = [
    MOVE.TAKE_DOWN,
    MOVE.BITE,
    MOVE.BODY_SLAM,
    MOVE.ROCK_SLIDE,
    MOVE.ANCIENT_POWER,
    MOVE.MUD_SHOT,
    MOVE.ICICLE_SPEAR,
    MOVE.DOUBLE_EDGE
]
EggMoves[SPECIES.CORSOLA] = [
    MOVE.ROCK_SLIDE,
    MOVE.SCREECH,
    MOVE.MIST,
    MOVE.AMNESIA,
    MOVE.BARRIER,
    MOVE.INGRAIN,
    MOVE.CONFUSE_RAY,
    MOVE.ICICLE_SPEAR
]
EggMoves[SPECIES.REMORAID] = [
    MOVE.AURORA_BEAM,
    MOVE.OCTAZOOKA,
    MOVE.SUPERSONIC,
    MOVE.HAZE,
    MOVE.SCREECH,
    MOVE.THUNDER_WAVE,
    MOVE.ROCK_BLAST
]
EggMoves[SPECIES.DELIBIRD] = [
    MOVE.AURORA_BEAM,
    MOVE.QUICK_ATTACK,
    MOVE.FUTURE_SIGHT,
    MOVE.SPLASH,
    MOVE.RAPID_SPIN,
    MOVE.ICE_BALL
]
EggMoves[SPECIES.MANTINE] = [
    MOVE.TWISTER,
    MOVE.HYDRO_PUMP,
    MOVE.HAZE,
    MOVE.SLAM,
    MOVE.MUD_SPORT,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.SKARMORY] = [
    MOVE.DRILL_PECK,
    MOVE.PURSUIT,
    MOVE.WHIRLWIND,
    MOVE.SKY_ATTACK,
    MOVE.CURSE
]
EggMoves[SPECIES.HOUNDOUR] = [
    MOVE.FIRE_SPIN,
    MOVE.RAGE,
    MOVE.PURSUIT,
    MOVE.COUNTER,
    MOVE.SPITE,
    MOVE.REVERSAL,
    MOVE.BEAT_UP,
    MOVE.WILL_O_WISP
]
EggMoves[SPECIES.PHANPY] = [
    MOVE.FOCUS_ENERGY,
    MOVE.BODY_SLAM,
    MOVE.ANCIENT_POWER,
    MOVE.SNORE,
    MOVE.COUNTER,
    MOVE.FISSURE
]
EggMoves[SPECIES.STANTLER] = [
    MOVE.SPITE,
    MOVE.DISABLE,
    MOVE.BITE,
    MOVE.SWAGGER,
    MOVE.PSYCH_UP,
    MOVE.EXTRASENSORY
]
EggMoves[SPECIES.TYROGUE] = [
    MOVE.RAPID_SPIN,
    MOVE.HI_JUMP_KICK,
    MOVE.MACH_PUNCH,
    MOVE.MIND_READER,
    MOVE.HELPING_HAND
]
EggMoves[SPECIES.SMOOCHUM] = [
    MOVE.MEDITATE,
    MOVE.PSYCH_UP,
    MOVE.FAKE_OUT,
    MOVE.WISH,
    MOVE.ICE_PUNCH
]
EggMoves[SPECIES.ELEKID] = [
    MOVE.KARATE_CHOP,
    MOVE.BARRIER,
    MOVE.ROLLING_KICK,
    MOVE.MEDITATE,
    MOVE.CROSS_CHOP,
    MOVE.FIRE_PUNCH,
    MOVE.ICE_PUNCH
]
EggMoves[SPECIES.MAGBY] = [
    MOVE.KARATE_CHOP,
    MOVE.MEGA_PUNCH,
    MOVE.BARRIER,
    MOVE.SCREECH,
    MOVE.CROSS_CHOP,
    MOVE.THUNDER_PUNCH
]
EggMoves[SPECIES.MILTANK] = [
    MOVE.PRESENT,
    MOVE.REVERSAL,
    MOVE.SEISMIC_TOSS,
    MOVE.ENDURE,
    MOVE.PSYCH_UP,
    MOVE.CURSE,
    MOVE.HELPING_HAND,
    MOVE.SLEEP_TALK
]
EggMoves[SPECIES.LARVITAR] = [
    MOVE.PURSUIT,
    MOVE.STOMP,
    MOVE.OUTRAGE,
    MOVE.FOCUS_ENERGY,
    MOVE.ANCIENT_POWER,
    MOVE.DRAGON_DANCE,
    MOVE.CURSE
]
EggMoves[SPECIES.TREECKO] = [
    MOVE.CRUNCH,
    MOVE.MUD_SPORT,
    MOVE.ENDEAVOR,
    MOVE.LEECH_SEED,
    MOVE.DRAGON_BREATH,
    MOVE.CRUSH_CLAW
]
EggMoves[SPECIES.TORCHIC] = [
    MOVE.COUNTER,
    MOVE.REVERSAL,
    MOVE.ENDURE,
    MOVE.SWAGGER,
    MOVE.ROCK_SLIDE,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.MUDKIP] = [
    MOVE.REFRESH,
    MOVE.UPROAR,
    MOVE.CURSE,
    MOVE.STOMP,
    MOVE.ICE_BALL,
    MOVE.MIRROR_COAT
]
EggMoves[SPECIES.POOCHYENA] = [
    MOVE.ASTONISH,
    MOVE.POISON_FANG,
    MOVE.COVET,
    MOVE.LEER,
    MOVE.YAWN
]
EggMoves[SPECIES.ZIGZAGOON] = [
    MOVE.CHARM,
    MOVE.PURSUIT,
    MOVE.SUBSTITUTE,
    MOVE.TICKLE,
    MOVE.TRICK
]
EggMoves[SPECIES.LOTAD] = [
    MOVE.SYNTHESIS,
    MOVE.RAZOR_LEAF,
    MOVE.SWEET_SCENT,
    MOVE.LEECH_SEED,
    MOVE.FLAIL,
    MOVE.WATER_GUN
]
EggMoves[SPECIES.SEEDOT] = [
    MOVE.LEECH_SEED,
    MOVE.AMNESIA,
    MOVE.QUICK_ATTACK,
    MOVE.RAZOR_WIND,
    MOVE.TAKE_DOWN,
    MOVE.FALSE_SWIPE
]
EggMoves[SPECIES.NINCADA] = [
    MOVE.ENDURE,
    MOVE.FAINT_ATTACK,
    MOVE.GUST,
    MOVE.SILVER_WIND
]
EggMoves[SPECIES.TAILLOW] = [
    MOVE.PURSUIT,
    MOVE.SUPERSONIC,
    MOVE.REFRESH,
    MOVE.MIRROR_MOVE,
    MOVE.RAGE,
    MOVE.SKY_ATTACK
]
EggMoves[SPECIES.SHROOMISH] = [
    MOVE.FAKE_TEARS,
    MOVE.SWAGGER,
    MOVE.CHARM,
    MOVE.FALSE_SWIPE,
    MOVE.HELPING_HAND
]
EggMoves[SPECIES.SPINDA] = [
    MOVE.ENCORE,
    MOVE.ROCK_SLIDE,
    MOVE.ASSIST,
    MOVE.DISABLE,
    MOVE.BATON_PASS,
    MOVE.WISH,
    MOVE.TRICK,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.WINGULL] = [
    MOVE.MIST,
    MOVE.TWISTER,
    MOVE.AGILITY,
    MOVE.GUST,
    MOVE.WATER_SPORT
]
EggMoves[SPECIES.SURSKIT] = [
    MOVE.FORESIGHT,
    MOVE.MUD_SHOT,
    MOVE.PSYBEAM,
    MOVE.HYDRO_PUMP,
    MOVE.MIND_READER
]
EggMoves[SPECIES.WAILMER] = [
    MOVE.DOUBLE_EDGE,
    MOVE.THRASH,
    MOVE.SWAGGER,
    MOVE.SNORE,
    MOVE.SLEEP_TALK,
    MOVE.CURSE,
    MOVE.FISSURE,
    MOVE.TICKLE
]
EggMoves[SPECIES.SKITTY] = [
    MOVE.HELPING_HAND,
    MOVE.PSYCH_UP,
    MOVE.UPROAR,
    MOVE.FAKE_TEARS,
    MOVE.WISH,
    MOVE.BATON_PASS,
    MOVE.SUBSTITUTE,
    MOVE.TICKLE
]
EggMoves[SPECIES.KECLEON] = [
    MOVE.DISABLE,
    MOVE.MAGIC_COAT,
    MOVE.TRICK
]
EggMoves[SPECIES.NOSEPASS] = [
    MOVE.MAGNITUDE,
    MOVE.ROLLOUT,
    MOVE.EXPLOSION
]
EggMoves[SPECIES.TORKOAL] = [
    MOVE.ERUPTION,
    MOVE.ENDURE,
    MOVE.SLEEP_TALK,
    MOVE.YAWN
]
EggMoves[SPECIES.SABLEYE] = [
    MOVE.PSYCH_UP,
    MOVE.RECOVER,
    MOVE.MOONLIGHT
]
EggMoves[SPECIES.BARBOACH] = [
    MOVE.THRASH,
    MOVE.WHIRLPOOL,
    MOVE.SPARK
]
EggMoves[SPECIES.LUVDISC] = [
    MOVE.SPLASH,
    MOVE.SUPERSONIC,
    MOVE.WATER_SPORT,
    MOVE.MUD_SPORT
]
EggMoves[SPECIES.CORPHISH] = [
    MOVE.MUD_SPORT,
    MOVE.ENDEAVOR,
    MOVE.BODY_SLAM,
    MOVE.ANCIENT_POWER
]
EggMoves[SPECIES.FEEBAS] = [
    MOVE.MIRROR_COAT,
    MOVE.DRAGON_BREATH,
    MOVE.MUD_SPORT,
    MOVE.HYPNOSIS,
    MOVE.LIGHT_SCREEN,
    MOVE.CONFUSE_RAY
]
EggMoves[SPECIES.CARVANHA] = [
    MOVE.HYDRO_PUMP,
    MOVE.DOUBLE_EDGE,
    MOVE.THRASH
]
EggMoves[SPECIES.TRAPINCH] = [
    MOVE.FOCUS_ENERGY,
    MOVE.QUICK_ATTACK,
    MOVE.GUST
]
EggMoves[SPECIES.MAKUHITA] = [
    MOVE.FAINT_ATTACK,
    MOVE.DETECT,
    MOVE.FORESIGHT,
    MOVE.HELPING_HAND,
    MOVE.CROSS_CHOP,
    MOVE.REVENGE,
    MOVE.DYNAMIC_PUNCH,
    MOVE.COUNTER
]
EggMoves[SPECIES.ELECTRIKE] = [
    MOVE.CRUNCH,
    MOVE.HEADBUTT,
    MOVE.UPROAR,
    MOVE.CURSE,
    MOVE.SWIFT
]
EggMoves[SPECIES.NUMEL] = [
    MOVE.HOWL,
    MOVE.SCARY_FACE,
    MOVE.BODY_SLAM,
    MOVE.ROLLOUT,
    MOVE.DEFENSE_CURL,
    MOVE.STOMP
]
EggMoves[SPECIES.SPHEAL] = [
    MOVE.WATER_SPORT,
    MOVE.STOCKPILE,
    MOVE.SWALLOW,
    MOVE.SPIT_UP,
    MOVE.YAWN,
    MOVE.ROCK_SLIDE,
    MOVE.CURSE,
    MOVE.FISSURE
]
EggMoves[SPECIES.CACNEA] = [
    MOVE.GRASS_WHISTLE,
    MOVE.ACID,
    MOVE.TEETER_DANCE,
    MOVE.DYNAMIC_PUNCH,
    MOVE.COUNTER
]
EggMoves[SPECIES.SNORUNT] = [
    MOVE.BLOCK,
    MOVE.SPIKES
]
EggMoves[SPECIES.AZURILL] = [
    MOVE.ENCORE,
    MOVE.SING,
    MOVE.REFRESH,
    MOVE.SLAM,
    MOVE.TICKLE
]
EggMoves[SPECIES.SPOINK] = [
    MOVE.FUTURE_SIGHT,
    MOVE.EXTRASENSORY,
    MOVE.SUBSTITUTE,
    MOVE.TRICK
]
EggMoves[SPECIES.PLUSLE] = [
    MOVE.SUBSTITUTE,
    MOVE.WISH
]
EggMoves[SPECIES.MINUN] = [
    MOVE.SUBSTITUTE,
    MOVE.WISH
]
EggMoves[SPECIES.MAWILE] = [
    MOVE.SWORDS_DANCE,
    MOVE.FALSE_SWIPE,
    MOVE.POISON_FANG,
    MOVE.PSYCH_UP,
    MOVE.ANCIENT_POWER,
    MOVE.TICKLE
]
EggMoves[SPECIES.MEDITITE] = [
    MOVE.FIRE_PUNCH,
    MOVE.THUNDER_PUNCH,
    MOVE.ICE_PUNCH,
    MOVE.FORESIGHT,
    MOVE.FAKE_OUT,
    MOVE.BATON_PASS,
    MOVE.DYNAMIC_PUNCH
]
EggMoves[SPECIES.SWABLU] = [
    MOVE.AGILITY,
    MOVE.HAZE,
    MOVE.PURSUIT,
    MOVE.RAGE
]
EggMoves[SPECIES.DUSKULL] = [
    MOVE.IMPRISON,
    MOVE.DESTINY_BOND,
    MOVE.PAIN_SPLIT,
    MOVE.GRUDGE,
    MOVE.MEMENTO,
    MOVE.FAINT_ATTACK
]
EggMoves[SPECIES.ROSELIA] = [
    MOVE.SPIKES,
    MOVE.SYNTHESIS,
    MOVE.PIN_MISSILE,
    MOVE.COTTON_SPORE
]
EggMoves[SPECIES.SLAKOTH] = [
    MOVE.PURSUIT,
    MOVE.SLASH,
    MOVE.BODY_SLAM,
    MOVE.SNORE,
    MOVE.CRUSH_CLAW,
    MOVE.CURSE,
    MOVE.SLEEP_TALK
]
EggMoves[SPECIES.GULPIN] = [
    MOVE.DREAM_EATER,
    MOVE.ACID_ARMOR,
    MOVE.SMOG,
    MOVE.PAIN_SPLIT
]
EggMoves[SPECIES.TROPIUS] = [
    MOVE.HEADBUTT,
    MOVE.SLAM,
    MOVE.RAZOR_WIND,
    MOVE.LEECH_SEED,
    MOVE.NATURE_POWER
]
EggMoves[SPECIES.WHISMUR] = [
    MOVE.TAKE_DOWN,
    MOVE.SNORE,
    MOVE.SWAGGER,
    MOVE.EXTRASENSORY,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.CLAMPERL] = [
    MOVE.REFRESH,
    MOVE.MUD_SPORT,
    MOVE.BODY_SLAM,
    MOVE.SUPERSONIC,
    MOVE.BARRIER,
    MOVE.CONFUSE_RAY
]
EggMoves[SPECIES.ABSOL] = [
    MOVE.BATON_PASS,
    MOVE.FAINT_ATTACK,
    MOVE.DOUBLE_EDGE,
    MOVE.MAGIC_COAT,
    MOVE.CURSE,
    MOVE.SUBSTITUTE
]
EggMoves[SPECIES.SHUPPET] = [
    MOVE.DISABLE,
    MOVE.DESTINY_BOND,
    MOVE.FORESIGHT,
    MOVE.ASTONISH,
    MOVE.IMPRISON
]
EggMoves[SPECIES.SEVIPER] = [
    MOVE.STOCKPILE,
    MOVE.SWALLOW,
    MOVE.SPIT_UP,
    MOVE.BODY_SLAM
]
EggMoves[SPECIES.ZANGOOSE] = [
    MOVE.FLAIL,
    MOVE.DOUBLE_KICK,
    MOVE.RAZOR_WIND,
    MOVE.COUNTER,
    MOVE.ROAR,
    MOVE.CURSE
]
EggMoves[SPECIES.RELICANTH] = [
    MOVE.MAGNITUDE,
    MOVE.SKULL_BASH,
    MOVE.WATER_SPORT,
    MOVE.AMNESIA,
    MOVE.SLEEP_TALK,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.ARON] = [
    MOVE.ENDEAVOR,
    MOVE.BODY_SLAM,
    MOVE.STOMP,
    MOVE.SMELLING_SALT
]
EggMoves[SPECIES.CASTFORM] = [
    MOVE.FUTURE_SIGHT,
    MOVE.PSYCH_UP
]
EggMoves[SPECIES.VOLBEAT] = [
    MOVE.BATON_PASS,
    MOVE.SILVER_WIND,
    MOVE.TRICK
]
EggMoves[SPECIES.ILLUMISE] = [
    MOVE.BATON_PASS,
    MOVE.SILVER_WIND,
    MOVE.GROWTH
]
EggMoves[SPECIES.LILEEP] = [
    MOVE.BARRIER,
    MOVE.RECOVER,
    MOVE.MIRROR_COAT,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.ANORITH] = [
    MOVE.RAPID_SPIN,
    MOVE.KNOCK_OFF,
    MOVE.SWORDS_DANCE,
    MOVE.ROCK_SLIDE
]
EggMoves[SPECIES.RALTS] = [
    MOVE.DISABLE,
    MOVE.WILL_O_WISP,
    MOVE.MEAN_LOOK,
    MOVE.MEMENTO,
    MOVE.DESTINY_BOND
]
EggMoves[SPECIES.BAGON] = [
    MOVE.HYDRO_PUMP,
    MOVE.THRASH,
    MOVE.DRAGON_RAGE,
    MOVE.TWISTER,
    MOVE.DRAGON_DANCE
]
EggMoves[SPECIES.CHIMECHO] = [
    MOVE.DISABLE,
    MOVE.CURSE,
    MOVE.HYPNOSIS,
    MOVE.DREAM_EATER
]
EGG_MOVES_TERMINATOR
