export enum WEATHER { 
    NONE = 0,
    SUNNY_CLOUDS = 1,
    SUNNY = 2,
    RAIN = 3,
    SNOW = 4,
    RAIN_THUNDERSTORM = 5,
    FOG_HORIZONTAL = 6,
    VOLCANIC_ASH = 7,
    SANDSTORM = 8,
    FOG_DIAGONAL = 9,
    UNDERWATER = 10,
    SHADE = 11,
    DROUGHT = 12,
    DOWNPOUR = 13,
    UNDERWATER_BUBBLES = 14,
    ROUTE119_CYCLE = 20,
    ROUTE123_CYCLE = 21 
}