export enum B_ANIM {
    // table ids for general animations
    CASTFORM_CHANGE = 0x0,
    STATS_CHANGE = 0x1,
    SUBSTITUTE_FADE = 0x2,
    SUBSTITUTE_APPEAR = 0x3,
    BAIT_THROW = 0x4,
    ITEM_KNOCKOFF = 0x5,
    TURN_TRAP = 0x6,
    ITEM_EFFECT = 0x7,
    SMOKEBALL_ESCAPE = 0x8,
    HANGED_ON = 0x9,
    RAIN_CONTINUES = 0xA,
    SUN_CONTINUES = 0xB,
    SANDSTORM_CONTINUES = 0xC,
    HAIL_CONTINUES = 0xD,
    LEECH_SEED_DRAIN = 0xE,
    MON_HIT = 0xF,
    ITEM_STEAL = 0x10,
    SNATCH_MOVE = 0x11,
    FUTURE_SIGHT_HIT = 0x12,
    DOOM_DESIRE_HIT = 0x13,
    FOCUS_PUNCH_SETUP = 0x14,
    INGRAIN_HEAL = 0x15,
    WISH_HEAL = 0x16,
    MON_SCARED = 0x17,
    GHOST_GET_OUT = 0x18,
    SILPH_SCOPED = 0x19,
    ROCK_THROW = 0x1A,
    SAFARI_REACTION = 0x1B,
    
    // special animations table
    LVL_UP = 0x0,
    SWITCH_OUT_PLAYER_MON = 0x1,
    SWITCH_OUT_OPPONENT_MON = 0x2,
    BALL_THROW = 0x3,
    SAFARI_BALL_THROW = 0x4,
    SUBSTITUTE_TO_MON = 0x5,
    MON_TO_SUBSTITUTE = 0x6,
    
    // status animation table
    STATUS_PSN = 0x0,
    STATUS_CONFUSION = 0x1,
    STATUS_BRN = 0x2,
    STATUS_INFATUATION = 0x3,
    STATUS_SLP = 0x4,
    STATUS_PRZ = 0x5,
    STATUS_FRZ = 0x6,
    STATUS_CURSED = 0x7,
    STATUS_NIGHTMARE = 0x8,
    STATUS_WRAPPED = 0x9 // does not actually exist
}